---
apiVersion: v1
kind: Service
metadata:
  name: web-go
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: http-web-go
  selector:
    app: web-go
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-go
spec:
  selector:
    matchLabels:
      app: web-go
  template:
    metadata:
      labels:
        app: web-go
    spec:
      containers:
      - name: web-go
        image: allanbtz/golang-web:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
          name: http-web-go
          protocol: TCP